version: '3.3'

services:
  
  # Usage:
  # 1. Build Image
  #   remove rmq-base's comment and `docker-compose build`
  # 2. Start container
  #   add rmq-base's comment and `docker-compose up`

  # rmq-base:
  #   image: rocketmq-base:4.3.1
  #   build:
  #     context: ./rmq-base
  #     args:
  #       RMQ_VERSION: 4.3.1
    

  rmq-namesrv:
    image: rocketmq-namesrv
    build: 
      context: ./rmq-namesrv
    networks: 
      - rmq-net
    ports:
      - '9876:9876'
    container_name: rmq-namesrv
    environment:
      - Xmx=512m
      - Xms=512m
      - Xmn=128m
      - ROCKETMQ_HOME=/root

  rmq-broker:
    image: rocketmq-broker
    build: 
      context: ./rmq-broker
    # network_mode: host
    networks: 
      - rmq-net
    ports:
      - '10911:10911'
      - '10909:10909'
    depends_on:
      - rmq-namesrv
    container_name: rmq-broker
    environment:
      - Xmx=512m
      - Xms=512m
      - Xmn=128m
      - ROCKETMQ_HOME=/root

  rmq-console:
    image: styletang/rocketmq-console-ng:latest
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks: 
      - rmq-net
    container_name: rmq-console-ng
    depends_on:
      - rmq-broker

networks: 
  rmq-net: